version: '3.1'
volumes:
  dbdata:
  postgres_data:
  bundle_cache:
services:
  postgres:
    container_name: gifts_api_development
    image: postgres:13.1
    ports:
      - '31027:5432'
    environment:
      - POSTGRES_USER=apptegy
      - POSTGRES_PASSWORD=apptegy
      - POSTGRES_DB=gifts_api_development
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /gifts-api-test-main
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - .:/gifts-api-test-main
      - bundle_cache:/bundle_cache
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle_cache
    stdin_open: true
    tty: true
